/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardExpensesIndexRouteImport } from './routes/dashboard/expenses/index'
import { Route as DashboardExpensesAddRouteImport } from './routes/dashboard/expenses/add'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardExpensesIndexRoute = DashboardExpensesIndexRouteImport.update({
  id: '/dashboard/expenses/',
  path: '/dashboard/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardExpensesAddRoute = DashboardExpensesAddRouteImport.update({
  id: '/dashboard/expenses/add',
  path: '/dashboard/expenses/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/expenses/add': typeof DashboardExpensesAddRoute
  '/dashboard/expenses': typeof DashboardExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/expenses/add': typeof DashboardExpensesAddRoute
  '/dashboard/expenses': typeof DashboardExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/expenses/add': typeof DashboardExpensesAddRoute
  '/dashboard/expenses/': typeof DashboardExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard'
    | '/dashboard/expenses/add'
    | '/dashboard/expenses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard'
    | '/dashboard/expenses/add'
    | '/dashboard/expenses'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/'
    | '/dashboard/expenses/add'
    | '/dashboard/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardExpensesAddRoute: typeof DashboardExpensesAddRoute
  DashboardExpensesIndexRoute: typeof DashboardExpensesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/expenses/': {
      id: '/dashboard/expenses/'
      path: '/dashboard/expenses'
      fullPath: '/dashboard/expenses'
      preLoaderRoute: typeof DashboardExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/expenses/add': {
      id: '/dashboard/expenses/add'
      path: '/dashboard/expenses/add'
      fullPath: '/dashboard/expenses/add'
      preLoaderRoute: typeof DashboardExpensesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardExpensesAddRoute: DashboardExpensesAddRoute,
  DashboardExpensesIndexRoute: DashboardExpensesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
